units: 
  #proxy variables
  q: u
  Q: U
  # padding
  Pu: u + 4
  XPu: Pu + 4
  screwSize: 1.5
  standoffSize: 2.5
points:
  zones:
    matrix:
      anchor:
        rotate: 20
      columns: 
        outer:
          key.column_net: P006
        pinky:
          key.column_net: P008
          key.splay: 0
        ring:
          key.column_net: P017
          key.splay: -5
          key.origin: [-1, -19]
          key.stagger: 12
        middle:
          key.column_net: P020
          key.stagger: 3
        index:
          key.column_net: P022
          key.stagger: -9
          key.splay: -3
          key.origin: [-1, -15]
        inner:
          key.column_net: P024
      rows:
        bottom:
          row_net: P107
        home:
          row_net: P102
        top:
          row_net: P101
        num:
          row_net: P010
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [0.5U, -23]
      columns:
        near:
          key.column_net: P009
        home:
          key.spread: 21.25
          key.splay: -30
          key.origin: [-11.75, -9]
          key.column_net: P113
        far:
          key.spread: 21.25
          key.splay: -30
          key.origin: [-9.5, -9]
          key.column_net: P031
      rows:
        thumb:
          row_net: P115
  rotate: -20

outlines: 
  keys: 
    - what: rectangle
      where: true
      bound: false
      size: [U,U]
  case:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_num
          shift: [-0.5Pu, 0.5Pu]
        - ref: matrix_outer_bottom
          shift: [-0.5Pu, -0.5Pu]
        - ref: matrix_index_bottom
          shift: [-0.5Pu, -1Pu]
        - ref: thumbfan_far_thumb
          shift: [0.17Pu, -2Pu]
        - ref: thumbfan_far_thumb
          shift: [0.5Pu, -0.5Pu]
        - ref: thumbfan_far_thumb
          shift: [0.5Pu, 0.5Pu]
        - ref: matrix_inner_num
          shift: [0.5Pu, 0.5Pu ]
        - ref: matrix_index_num
          shift: [0.5Pu, 0.5Pu]
        - ref: matrix_middle_num
          shift: [0.5Pu,0.5Pu]
        - ref: matrix_middle_num
          shift: [-0.5Pu,0.5Pu]
        - ref: matrix_ring_num
          shift: [-0.5Pu,0.5Pu]
        - ref: matrix_outer_num
          shift: [-0.5Pu,0.5Pu]
      fillet: 3
  xlCase:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_num
          shift: [-0.5XPu, 0.5XPu]
        - ref: matrix_outer_bottom
          shift: [-0.5XPu, -0.5XPu]
        - ref: matrix_index_bottom
          shift: [-0.5XPu, -1XPu]
        - ref: thumbfan_far_thumb
          shift: [0.17XPu, -2XPu]
        - ref: thumbfan_far_thumb
          shift: [0.5XPu, -0.5XPu]
        - ref: thumbfan_far_thumb
          shift: [0.5XPu, 0.5XPu]
        - ref: matrix_inner_num
          shift: [0.5XPu, 0.5XPu ]
        - ref: matrix_index_num
          shift: [0.5XPu, 0.5XPu]
        - ref: matrix_middle_num
          shift: [0.5XPu,0.5XPu]
        - ref: matrix_middle_num
          shift: [-0.5XPu,0.5XPu]
        - ref: matrix_ring_num
          shift: [-0.5XPu,0.5XPu]
        - ref: matrix_outer_num
          shift: [-0.5XPu,0.5XPu]
      fillet: 3
  combo:
    - name: case
    - operation: subtract
      name: keys
  mounting:
    - what: circle
      radius: screwSize
      where:
        ref: [matrix_outer_bottom]
        shift: [-0.45u, -0.45u]
    - what: circle
      radius: screwSize
      where:
        ref: [matrix_middle_num]
        shift: [-0.1u, 0.4u]
    - what: circle
      radius: screwSize
      where:
        ref: [matrix_inner_num]
        shift: [0.5u, 0u]
    - what: circle
      radius: screwSize
      where:
        ref: [matrix_index_bottom]
        shift: [-0.5u, -1u]
    - what: circle
      radius: screwSize
      where:
        ref: [thumbfan_far_thumb]
        shift: [0.45u, 0.45u]
    - what: circle
      radius: screwSize
      where:
        ref: [matrix_outer_num]
        shift: [-0.4u, 0.4u] 
  standoff:
    - what: circle
      radius: standoffSize
      where:
        ref: [matrix_outer_bottom]
        shift: [-0.45u, -0.45u]
    - what: circle
      radius: standoffSize
      where:
        ref: [matrix_middle_num]
        shift: [-0.1u, 0.4u]
    - what: circle
      radius: standoffSize
      where:
        ref: [matrix_inner_num]
        shift: [0.5u, 0u]
    - what: circle
      radius: standoffSize
      where:
        ref: [matrix_index_bottom]
        shift: [-0.5u, -1u]
    - what: circle
      radius: standoffSize
      where:
        ref: [thumbfan_far_thumb]
        shift: [0.45u, 0.45u]
    - what: circle
      radius: standoffSize
      where:
        ref: [matrix_outer_num]
        shift: [-0.4u, 0.4u] 

pcbs:
   tutorial:
    outlines:
      main:
        outline: case
    footprints: 
      cherrymx_hotswap:
        what: mx
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode: 
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0,-5]
      nicenano: 
        what: nice_nano
        params: 
          orientation: down
        where: 
        - ref: thumbfan_far_thumb
          shift: [-14,-32]
          rotate: 169
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
        - ref: thumbfan_far_thumb
          shift: [-14,-33]
          rotate: 169
      jstph:
        what: jstph
        params:
          pos: RAW
          neg: GND
        where:
        - ref: thumbfan_far_thumb
          shift: [-14,-28]
          rotate: 169
      m2mountholeTL:
       what: mountinghole
       where:
        ref: [matrix_outer_num]
        shift: [-0.4u, 0.4u]
      m2mountholeBR:
       what: mountinghole
       where:
        ref: [thumbfan_far_thumb]
        shift: [0.45u, 0.45u]
      m2mountholeML:
       what: mountinghole
       where:
        ref: [matrix_index_bottom]
        shift: [-0.5u, -1u]
      m2mountholeTR:
       what: mountinghole
       where:
        ref: [matrix_inner_num]
        shift: [0.5u, 0u]
      m2mountholeTM:
       what: mountinghole
       where:
        ref: [matrix_middle_num]
        shift: [-0.1u, 0.4u]
      m2mountholeBL:
       what: mountinghole
       where:
        ref: [matrix_outer_bottom]
        shift: [-0.45u, -0.45u]
cases:
  bottom:
    - name: case
      extrude: 1
  xlBottom:
    - name: xlCase
      extrude: 1
  _outerWall:
    - name: xlCase
      extrude: 5.6
  _innerWall:
    - name: case
      extrude: 5.6
  wall: 
    - what: case
      name: _outerWall
      operation: add
    - what: case
      name: _innerWall
      operation: subtract
  _holes:
    - name: mounting
      extrude: 4
  _standoffs:
    - name: standoff
      extrude: 4
  case: 
    - what: case
      name: _standoffs
      operation: add
    - what: case
      name: _holes
      operation: subtract
    - what: case
      name: xlBottom
      operation: add
    - what: case
      name: wall
      operation: add
